#!/bin/bash

//update catalog
sudo apt update
//upgrade distribution
sudo apt full-upgrade
//installing packages 
sudo apt install unzip wget python3-pip man libgl1-mesa-glx libegl1-mesa libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 gdb python mlocate command-not-found bash-completion git mesa-utils  

sudo apt-file update
sudo update-command-not-found

//fix a cuda warning
echo -e -n "[automount]\n ldconfig = false" > wsl.conf
echo -e -n "# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:\n# [automount]\n# ldconfig = false\n/usr/lib/wsl2/lib\n" > /etc/ld.so.conf.d/ld.wsl.conf
sudo mkdir /usr/lib/wsl2
sudo cp -r -p /usr/lib/wsl/lib /usr/lib/wsl2/
sudo rm /usr/lib/wsl2/lib/libcuda.so.*
sudo ldconfig

mkdir ~/workspace
cd ~/workspace
mkdir miniconda
cd miniconda

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh
sudo ln ~/miniconda3/bin/conda /usr/local/bin/conda

#conda upgrade -n base conda
conda update --all

cd /mnt/e/stable-diffusion/stable-diffusion-main/
conda env create -f environment.yaml

conda init bash

exit 0

#restart then run windows11_debian_wsl2_stage2.sh in debian wsl2
